#!/bin/bash

# alias
if [ `uname -s` = "Darwin" ]
then
    alias ls='ls -G --color'
    #alias ls='ls -G -G'
else
    alias ls='ls -G --color'
fi
alias l='ls'
alias ll='ls -l'
alias la='ls -a'
alias lla='ls -al'
alias lal='ls -al'
alias cls='clear'
alias tm='tmux'
alias tma='tm a'
alias scpr='rsync -avP'
alias mwget='aria2c -c -s 15 -x 15 --file-allocation=none'
alias tmux='TERM=xterm-256color tmux'
alias grep="grep --color=auto"
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'

# export
export PS1="${debian_chroot:+($debian_chroot)}\u@\h:\w\$ "
export CLICOLOR=1
export LSCOLORS=dxfxxxxxbxegedbxbxdxdx
export PYTHONDONTWRITEBYTECODE=1
export LANGUAGE=en_US:en
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export TERM=screen-256color

# source git scripts
GIT_COMPLETION_PATH=~/.vim/confs/scripts/git-completion.bash
if [ -f $GIT_COMPLETION_PATH ]
then
    source $GIT_COMPLETION_PATH
fi

# source ssh scripts
SSH_COMPLETION_PATH=~/.vim/confs/scripts/ssh-completion.bash
if [ -f $SSH_COMPLETION_PATH ]
then
    source $SSH_COMPLETION_PATH
fi

# source ext
if [ -f ~/.bash_ext ]
then
    source ~/.bash_ext
fi

# source bashrc
if [ -f ~/.bashrc ]
then
    source ~/.bashrc
fi
