#!/bin/bash

# bin
if [ -e ~/bin ]
then
    export PATH=~/bin:$PATH
fi

# pyenv
if [ -e ~/.pyenv ]
then
    export PYENV_ROOT="$HOME/.pyenv"
    export PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"
fi

# workspace
if [ -f ~/.workspace.dmg.sparseimage ]
then
    function workspacemount {
        hdiutil attach ~/.workspace.dmg.sparseimage -mountpoint /Volumes/workspace;
        ln -s /Volumes/workspace ~/workspace
    }

    function workspaceumount {
        hdiutil detach /Volumes/workspace
        rm ~/workspace
    }
fi

# translate man help page to pdf format
if [ `uname -s` = 'Darwin' ]
then
    function man2pdf {
        man -t $1 | open -f -a /Applications/Preview.app
    }
fi

# src_count
function src_count {
    type=$1
    total=0
    for x in `find ./* -type f -name "*.$type"`;
    do
        single=`cat $x|wc -l`
        total=$total+$single
    done

    echo $total|bc
}
