#!bash

function src_count {
    type=$1
    total=0
    for x in `find ./* -type f -name "*.$type"`;
    do
        single=`cat $x|wc -l`
        total=$total+$single
    done

    echo $total|bc
}

# translate man help page to pdf format, only for MAC
function man2pdf {
    man -t $1 | open -f -a /Applications/Preview.app
}

#bin
if [ -e ~/bin ]
then
    export PATH=~/bin:$PATH
fi

#pyenv
if [ -e ~/.pyenv ]
then
    export PYENV_ROOT="$HOME/.pyenv"
    export PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init -)"
fi
